version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
      - redis
    networks:
      - node-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
