# version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    # environment:
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    #volumes:
    #  - .:/usr/src/app
    networks:
      - node-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  - node_modules
  - dbdata6:

networks:
  node-network:
    driver: bridge
